### ISSUE TITLE
how to run it in docker?

### ISSUE THREAD

**Issue by xPomaHx** [porla/porla#2]
I use this image `node:10`

```internal/modules/cjs/loader.js:807
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^

Error: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by /app/node_modules/@porla/libtorrent/prebuilds/linux-x64/node-napi.node)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:807:18)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/app/node_modules/@porla/libtorrent/index.js:5:18)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
```

index.js

```const porla     = require('porla');
const dashboard = require('@porla-contrib/dashboard');
 
const app = porla({
    plugins: [ dashboard({ port: 7090 }) ]
});
app.on('torrent.finished', ({ torrent }) => [
    sendMessage(`Torrent ${torrent.name} finished.`)
]);
```

**Comment by vktr** [comment]
Hey @xPomaHx! You need to install the C++ runtime in the Docker image, which base image are you using?
